name: Deploy to EC2
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Add EC2 instance to known hosts
        run: |
          echo "${{ secrets.EC2_HOST }} $(ssh-keyscan -t rsa ${{ secrets.EC2_HOST }})" >> ~/.ssh/known_hosts
      
      - name: Deploy code to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p ~/parkingLot-dor-yon'
          scp -o StrictHostKeyChecking=no -r * ubuntu@${{ secrets.EC2_HOST }}:~/parkingLot-dor-yon/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo apt-get update'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'sudo apt-get install -y python3-pip'
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'pip3 install -r ~/parkingLot-dor-yon/requirements.txt'
          ssh -n -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'cd ~/parkingLot-dor-yon && nohup python3 server.py > server.log 2>&1 &'
          exit
